### ISSUE TITLE
Error when running test-runners

### ISSUE THREAD

**Issue by verdammelt** [exercism/tooling-invoker#30]
(I'm _assuming_ that this is a problem of the tooling-invoker...)

Working with the latest images from the latest `development-environment` I cannot succesfully run the ruby-test-runner.

The output shown on the `maintaining/submissions` page is:

```
exceptioned


STDOUT:
------



STDERR:
------
docker: Error response from daemon: invalid mode: /mnt/exercism-iteration.
See 'docker run --help'.
```

Looking at the `tooling-invoker` logs I see it ran this command:

`docker container run -a stdout -a stderr --stop-timeout 0 --rm -v /Users/mark/SRC/exercism/development-environment:/tmp/tmp/exercism-tooling-jobs/13542007-8304-4a91-ae79-8269f437bca7-8c520cb5f44e8afcd787708cfdedc1db/code:/mnt/exercism-iteration -l exercism-13542007-8304-4a91-ae79-8269f437bca7-9038192beab1b01ea3fe006cd105a863 --network none -m 1GB exercism/ruby-test-runner:latest lasagna /mnt/exercism-iteration/ /mnt/exercism-iteration/`

Which produces the same error when I run it by hand.

I guess one of the several `/mnt/exercism-iteration` instances in that command line is in error?

**Comment by iHiD** [comment]
```
-v /Users/mark/SRC/exercism/development-environment:/tmp/tmp/exercism-tooling-jobs/13542007-8304-4a91-ae79-8269f437bca7-8c520cb5f44e8afcd787708cfdedc1db/code:/mnt/exercism-iteration
```

@ErikSchierboom There's something not good going on here... ^^

@verdammelt Could you paste your stack.yml pls?

**Comment by iHiD** [comment]
@verdammelt Does it work with this?

```-v /Users/mark/SRC/exercism/development-environment/tmp/exercism-tooling-jobs/13542007-8304-4a91-ae79-8269f437bca7-8c520cb5f44e8afcd787708cfdedc1db/code:/mnt/exercism-iteration```

**Comment by verdammelt** [comment]
RE: stack.yml - to debug the problem i 'rolled back' to using the stack.default.yml file. I am currently in teh process of debugging what might be a (super minor) issue with that, but when i have the system back up and runnig I'll paste it in here.

**Comment by iHiD** [comment]
https://github.com/exercism/development-environment/blob/master/stack.default.yml#L36-L38

Try removing the `:/tmp` from that and see if it helps.

@ErikSchierboom will know this straight away probably. He'll be back just before the call.

**Comment by verdammelt** [comment]
Removeing the `:/tmp` did fix the problem (I was confused at first because i expected the tests to *pass* (was't actually looking at the implementation I was submitting...) but they didn't so i still got 'failed' from the test runner).

I'll close this issue and open a PR over in development-environment.
